# Site settings
title: ennui
description: the rest is silence
url: armandioalif.github.com/ennui
baseurl: armandioalif.github.com/ennui

disqus_shortname: obrol
google_analytics: false #if set to "true" modify the google_analytycs.html, set to false otherwise

# Links settings
links:
  - name:         indeks
    url:          armandioalif.github.com/ennui
  - name:         buku
    url:          armandioalif.github.com/ennui/buku
    external:     false
  - name:         terjemahan
    url:          armandioalif.github.com/ennui/terjemahan
    external:     false
    external:     false
  - name:         profil
    url:          armandioalif.github.com/ennui/profil
    external:     false

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
