# Site settings
title: ennui 
description: the rest is silence
url: https://armandioalif.github.io/ennui
baseurl: ennui/

disqus_shortname: obrol
google_analytics: false #if set to "true" modify the google_analytycs.html, set to false otherwise

# Links settings
links:
  - name:         indeks
    url:          /
  - name:         terjemahan
    url:          /terjemahan
    external:     false
  - name:         buku
    url:          /archive
    external:     false
    external:     false
  - name:         profil
    url:          http://github.com/kuoa
    external:     true

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
